# -*- coding: utf-8 -*-
"""p8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OK2Nv-hTkxjGBbOmRzhWV-iDHWqBqfoa
"""

# ------------------------------------------------------------
# PLAYLIST ORGANIZER – PROJECT OUTLINE (COMMENT VERSION)
# ------------------------------------------------------------

# 1 — INTRODUCTION
# This project creates a simple Playlist Organizer using:
# - Lists (main structure)
# - Light use of dictionaries (song details)
# - A menu-driven program
# - Basic user interaction
# No code is included here—only the conceptual steps.

# ------------------------------------------------------------
# 2 — DATA STRUCTURES
# Playlist:
# - A list that stores all songs.
# - Each song is one item in the list.

# Song Representation:
# - Each song is a dictionary containing details such as:
#   "title"
#   "artist"
#   "album" (optional)
#   "length" (optional)

playlist = []
juno = {
    "title": "Juno",
    "artist": "Sabrina Carpenter",
    "album": "Short 'n Sweet",
    "length": "3:43"
}
add_up_my_love = {
    "title": "Add Up My Love",
    "artist": "Clairo",
    "album": "Charm",
    "length": "3:24"
}
marcel = {
    "title": "Marcel",
    "artist": "Her's",
    "album": "Songs of Her's",
    "length": "3:07"
}
over_the_moon = {
    "title": "Over the Moon",
    "artist": "The Marias",
    "album": "Superclean Vol. II",
    "length": "3:02"
}
finally_alone = {
    "title": "Finally Alone",
    "artist": "Mac Demarco",
    "album": "Here Comes the Cowboy",
    "length": "2:24"
}
for song in [juno, add_up_my_love, marcel, over_the_moon, finally_alone]:
  playlist.append(song)
#print(playlist)

# ------------------------------------------------------------
# 4 — ADD A SONG
# Steps:
# 1. Ask the user for song details (title, artist, etc.).
# 2. Create a dictionary using those details.
# 3. Append the dictionary to the playlist list.
# 4. Confirm that the song was added.

def add_song(playlist):
   print("\n--- Add a Song ---")

   title = input("Enter song title: ")
   artist = input("Enter the artist: ")
   album = input("Enter the album (optional): ")
   length = input("Enter the length (optional): ")

   song = {
       "title": title,
       "artist": artist,
       "album": album,
       "length": length
   }

   playlist.append(song)

   print(f"\n'{title}' by {artist} has been added to your playlist.")

# ------------------------------------------------------------
# 5 — VIEW PLAYLIST
# Steps:
# 1. Check if the playlist is empty.
# 2. If empty, display a message.
# 3. Otherwise, loop through the list and display each song.
# 4. Show song numbers (index + 1) for user reference.

def view_playlist(playlist):
  if playlist:
    count = 0
    for song in playlist:
      count += 1
      print(count, song)
  else:
    print("Playlist does not conatin any songs.")

# ------------------------------------------------------------
# 6 — REMOVE A SONG
# Steps:
# 1. Display the playlist with song numbers.
# 2. Ask the user which song number to remove.
# 3. Convert the number to a list index.
# 4. Remove the corresponding item from the list.
# 5. Confirm removal.

def delete_song(playlist):
  print("\n--- Remove a Song ---")
  if not playlist:
        print("Your playlist is empty.")
        return

  for i, song in enumerate(playlist, start=1):
        print(i, song["title"], "-", song["artist"])

  choice = input("Enter the number of the song to remove: ")

  index = int(choice) - 1

  removed = playlist.pop(index)

  print("Removed:", removed["title"])


# ------------------------------------------------------------
# 7 — REORDER SONGS (OPTIONAL)
# Steps:
# 1. Display the playlist with numbers.
# 2. Ask the user which song to move.
# 3. Ask where it should be moved.
# 4. Remove the song from its current position.
# 5. Insert it into the new position.

def reorder_songs(playlist):
    print("\n--- Reorder Songs ---")

    if not playlist:
        print("Your playlist is empty.")
        return

    for i, song in enumerate(playlist, start=1):
        print(i, song["title"], "-", song["artist"])

    old_pos = int(input("Which song number do you want to move? "))

    new_pos = int(input("Move it to which position? "))

    old_index = old_pos - 1
    new_index = new_pos - 1

    song = playlist.pop(old_index)
    playlist.insert(new_index, song)

    print("Song moved.")


# ------------------------------------------------------------
# 8 — SEARCH FOR SONGS (OPTIONAL)
# Steps:
# 1. Ask the user what field to search by (title or artist).
# 2. Loop through the playlist.
# 3. Compare the user's search term with the dictionary values.
# 4. Display any matching songs.

def search_songs(playlist):
    print("\n--- Search Songs ---")

    if not playlist:
        print("Your playlist is empty.")
        return

    term = input("Enter a word to search for (title or artist): ").lower()

    print("\nResults:")
    found_any = False

    for i, song in enumerate(playlist, start=1):
        title = song["title"].lower()
        artist = song["artist"].lower()

        if term in title or term in artist:
            print(i, song["title"], "-", song["artist"])
            found_any = True

    if not found_any:
        print("No matching songs found.")

# ------------------------------------------------------------
# 3 — MAIN PROGRAM LOOP
# The program will:
# - Continuously display a menu of options
# - Accept user input
# - Perform actions based on the user's choice
# - Continue until the user chooses to quit

# Possible menu options:
# - Add a song
# - View playlist
# - Remove a song
# - Reorder songs
# - Search for songs
# - Quit

def show_menu():
    print("\n--- Playlist Menu ---")
    print("1. Add a song")
    print("2. View playlist")
    print("3. Remove a song")
    print("4. Reorder songs")
    print("5. Search for songs")
    print("6. Quit")

running = True

while running:
    show_menu()
    choice = input("Enter your choice: ")

    if choice == "1":
        add_song(playlist)

    elif choice == "2":
        view_playlist(playlist)

    elif choice == "3":
        delete_song(playlist)

    elif choice == "4":
        reorder_songs(playlist)

    elif choice == "5":
        search_songs(playlist)

    elif choice == "6":
        print("Goodbye!")
        running = False

    else:
        print("Invalid choice. Please try again.")

# ------------------------------------------------------------
# END OF OUTLINE
# ------------------------------------------------------------